AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2 for IPv6, bastion host, by Wolfgang Unger ' 


Parameters:

  ParentVPCStack:
    Description: "Stack name of parent VPC stack"
    Type: String
    Default: "IPv6VPC"

  OwnerName:
    Description: An owner name, used in tags
    Type: String
    Default: "wolfgang.unger"

  ImageId:
    Description: Inform the image id
    Type: String
    #Default: "ami-027d95b1c717e8c5d" ## eu-west-2
    Default: "ami-0766b4b472db7e3b9" ## eu-west-1
################## Resources ##############################    
Resources:

  BastionKeyPair:
    Type: 'AWS::EC2::KeyPair'
    Properties:
      KeyName: BastionKeyPair

  BastionServer: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref ImageId
      KeyName: !Ref BastionKeyPair 
      InstanceType: t3.micro     
      SubnetId:  
        Fn::ImportValue: !Sub '${ParentVPCStack}-SubnetAPublic'
      IamInstanceProfile: 
        Fn::ImportValue: SSMInstanceProfile
      Tags: 
        - Key: "Owner"
          Value: !Ref OwnerName
        - Key: "Name"
          Value: BastionServer

Outputs:

  BastionServerInstanceId:
    Value: !Ref BastionServer
    Description: BastionServerInstanceId
    Export:
      Name: BastionServerInstanceId

  KeyPair:
    Value: !Ref BastionServer
    Description: BastionKeyPair
    Export:
      Name: BastionKeyPair        