AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Fargate Service in private subnet. Not connected to ALB
Parameters:

  ParentVPCStack:
    Description: "Stack name of the parent VPC stack"
    Type: String
    Default: IPv6VPC

  EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
        Default: fargate-example

  ImageUrl:
    Type: String
    Default: xxx.dkr.ecr.eu-west-1.amazonaws.com/ecs-repository-ipv6:httpd
    Description: The url of a docker image 
    
  ContainerPort:
    Type: Number
    Default: 80
    Description: What port number the application inside the docker container is binding to

  Path:
    Type: String
    Default: "*"
    Description: A path on the public load balancer that this service
                 should be connected to. Use * to send all load balancer
                 traffic to this service.
  HealthCheckPath:
    Type: String
    Default: "/"
    Description: path for the LB healthcheck

  Priority:
    Type: Number
    Default: 1
    Description: The priority for the routing rule added to the load balancer.
                 This only applies if your have multiple services which have been
                 assigned to different paths on the load balancer.

Resources:

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref AWS::StackName
      Cpu: 1024
      Memory: 2048
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn:
        Fn::ImportValue:
          !Join [':', [!Ref 'EnvironmentName', 'ECSTaskExecutionRole']]
      ContainerDefinitions:
        - Name: !Ref AWS::StackName
          Cpu: 1024
          Memory: 2048
          Image: !Ref 'ImageUrl'
          PortMappings:
            - ContainerPort: !Ref 'ContainerPort'       
            # vpc endpoint required for cloudwatch logs  
          LogConfiguration:
              LogDriver: awslogs
              Options:
                  awslogs-group: !Ref AWS::StackName
                  awslogs-region: !Ref AWS::Region     
                  awslogs-stream-prefix: "fargate"       

  CloudWatchLogsGroup:
        Type: AWS::Logs::LogGroup
        Properties: 
            LogGroupName: !Ref AWS::StackName
            RetentionInDays: 365  

  Service:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Ref AWS::StackName
      Cluster: 
        Fn::ImportValue:
          !Join [':', [!Ref 'EnvironmentName', 'ClusterName']]
      LaunchType: FARGATE
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 75
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - Fn::ImportValue:
                !Join [':', [!Ref 'EnvironmentName', 'FargateContainerSecurityGroup']]
          Subnets:
            - Fn::ImportValue:
                !Join ['-', [!Ref 'ParentVPCStack', 'SubnetAPrivate']]
            - Fn::ImportValue:
                !Join ['-', [!Ref 'ParentVPCStack', 'SubnetBPrivate']]     
      TaskDefinition: !Ref 'TaskDefinition'




