AWSTemplateFormatVersion: "2010-09-09"
Description: "R53 Recordset for Web Server"

Parameters:
  ParentVPCStack:
    Description: "the base vpc stack"
    Type: String
    Default: IPv6VPC

  URL:
    Description: "URL for RS"
    Type: String
    Default: "alb.ireland.sccbrasil.com"

Resources:
  ApiServerRecordset:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Ref URL
      HostedZoneId: !ImportValue "DNS-HostedZoneId"
      Type: A
      #TTL: "300"
      Comment: RecordsSet for Web Server LB
      AliasTarget:
        HostedZoneId: !ImportValue "LB-Web-Server-HostedZoneId"
        DNSName: !ImportValue "LB-Web-Server"
